version: '3.4'

services:

  es742-001:
    image: elasticsearch:7.4.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es742-001
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - elknet

  kibana742:
    image: kibana:7.4.2
    depends_on:
      - es742-001
    ports:
      - 5601:5601
    environment:
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: http://es742-001:9200
    networks:
      - elknet

  logstash742:
    image: logstash:7.4.2
    depends_on:
      - es742-001
    networks:
      - elknet


networks:
  elknet:
    driver: bridge
    name: elknet

volumes:
  esdata01:
    driver: local
