version: '3.7'

services:

  es742:
    image: haxqer/es:7.4.2
    container_name: es742
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es742
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - data-es742:/usr/share/elasticsearch/data
    networks:
      - elknet

  kibana742:
    image: kibana:7.4.2
    container_name: kibana742
    depends_on:
      - es742
    environment:
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: http://es742:9200
    volumes:
      - data-kibana742:/usr/share/kibana/data
    networks:
      - elknet

  logstash742:
    image: haxqer/logstash:7.4.2
    container_name: logstash742
    depends_on:
      - es742
    environment:
      TZ: "Asia/Shanghai"
      ELASTICSEARCH_HOSTS: http://es742:9200
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
    networks:
      - elknet


networks:
  elknet:
    driver: bridge
    name: elknet


volumes:
  data-kibana742:
    driver: local
  data-es742:
    driver: local

