version: '3.4'

services:

  es01:
    image: elasticsearch:7.1.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: kibana:7.1.1
    depends_on:
      - es01
    ports:
      - 5601:5601
    environment:
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: http://es01:9200
#      - elasticsearch.hosts="http://es01:9200"
    networks:
      - esnet

networks:
  esnet:
    driver: bridge

volumes:
  esdata01:
    driver: local
